name: hoobky
favicon: null
layout_spectrum: 0.4829811751842499
typography_spectrum: 0.031693174969404936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5487496207933873
  lightness: 0.7291107610799372
  saturation: 0.017202841117978096
  rhythmicContrast: 0.2562876606825739
purpose: []
